# (int) How long to wait between screenshots, in seconds.
screenshots_interval: 60

# (int) Maximum image height in pixels (maximum width always = 10000px).
img_max_height: 1000

# (int) JPEG compression level (0-100).
img_compression: 70

# (string|null) Where the log files should be saved locally. If null, no
# local files will be created.
local_path: "./log"

# (string|null) If given, send all data to the receiving script on the
# server (ex: https://somedomain.com/cs.php).
remote_host: null

# (string|null) If the receiving script requires a password to accept
# the data (see top of cs.php to set a password).
remote_password: null

# (string|int|null) When watching multiple computers, you can give each
# one a unique instance ID to organize data into different directories.
remote_instance_id: null
